const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/product-2.jpeg",
      price: 120,
      countInStock:10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
        _id: "2",
        name: "Addias Fit Shirt",
        category: "Shirts",
        image: "/images/product-1.jpeg",
        price: 100,
        countInStock:20,
        brand: "Addidas",
        rating: 4.0,
        numReviews: 10,
        description: "high quality product",
      },
      {
        _id: "3",
        name: "Lacoste free Shirt",
        category: "Shirts",
        image: "/images/product-2.jpeg",
        price: 120,
        countInStock:0,
        brand: "Lacoste",
        rating: 4.8,
        numReviews: 17,
        description: "high quality product",
      },
      {
        _id: "4",
        name: "Nike Slim Pant",
        category: "Pants",
        image: "/images/product-1.jpeg",
        price: 78,
        countInStock:15,
        brand: "Nike",
        rating: 4.5,
        numReviews: 14,
        description: "high quality product",
      },
      {
        _id: "5",
        name: "Puma Slim Pant",
        category: "Pants",
        image: "/images/product-2.jpeg",
        price: 65,
        countInStock:5,
        brand: "Puma",
        rating: 4.5,
        numReviews: 10,
        description: "high quality product",
      },
      {
        _id: '6',
        name: "Addidas Slim Pant",
        category: "Shirts",
        image: "/images/product-1.jpeg",
        price: 139,
        countInStock:12,
        brand: "Addidas",
        rating: 4.5,
        numReviews: 13,
        description: "high quality product",
      },
  ],
};


module.exports = data;